phrase:
  access_token: 2fd379951a8f303619e42f64461cb78b9437f62eaee0546656e6745962e10f8a
  project_id: ade0ad79d7ca214be4251a77d40fbb7f
  push:
    sources:
      params:
        file_format: nested_json
        
  pull:
    targets:
    
    - file: test2.json
      params:
        file_format: nested_json
       
